#!/usr/bin/env bash
#Create script that displays 1- 100 
for i in {1..100}
do
	    str=
	        ((i % 3 == 0)) && str="Fizz"
		    ((i % 5 == 0)) && str+="Buzz"
		        if [ -z "$str" ]
				    then
					    	echo "$i"
						    else
							    	echo "$str"
								    fi
							    done
